Repository softeerbootcamp-3nd/I-Atcha-BE, pull requests merged in 2024-01, with the labels that each got.

#16 🎉[FEAT] 홈 기능 구현
  src/main/java/softee5/demo/controller/HomeController.java
  src/main/java/softee5/demo/controller/MemoController.java
  src/main/java/softee5/demo/dto/ParkingLotDto.java
  src/main/java/softee5/demo/dto/request/HomeRequestDto.java
  src/main/java/softee5/demo/dto/response/HomeResponseDto.java
  src/main/java/softee5/demo/dto/response/MemoResponseDto.java
  src/main/java/softee5/demo/entity/Image.java
  src/main/java/softee5/demo/entity/Member.java
  src/main/java/softee5/demo/entity/Memo.java
  src/main/java/softee5/demo/repository/ParkingRepository.java
  src/main/java/softee5/demo/service/HomeService.java
  src/main/java/softee5/demo/service/MemoService.java
  src/main/resources/data.sql
Labels: feat

#20 🎉[FEAT] : 주차 장소를 벗어났는지 확인하는 기능 추가
  src/main/java/softee5/demo/controller/LocationController.java
  src/main/java/softee5/demo/dto/request/UserDto.java
  src/main/java/softee5/demo/entity/Member.java
  src/main/java/softee5/demo/repository/MemberRepository.java
  src/main/java/softee5/demo/service/LocationService.java
  src/main/java/softee5/demo/service/ParkingService.java
  src/main/java/softee5/demo/utils/Compute.java
Labels: feat

#21 Yang soeun/history
  src/main/java/softee5/demo/AtchaApplication.java
  src/main/java/softee5/demo/controller/HomeController.java
  src/main/java/softee5/demo/controller/MemoController.java
  src/main/java/softee5/demo/dto/HistoryDto.java
  src/main/java/softee5/demo/dto/ParkingLot.java
  src/main/java/softee5/demo/dto/request/HomeExitRequestDto.java
  src/main/java/softee5/demo/dto/request/HomeRequestDto.java
  src/main/java/softee5/demo/dto/request/MemoRequestDto.java
  src/main/java/softee5/demo/dto/response/HistoryDetailResponseDto.java
  src/main/java/softee5/demo/dto/response/HistoryListResponseDto.java
  src/main/java/softee5/demo/dto/response/HomeResponseDto.java
  src/main/java/softee5/demo/dto/response/MemoResponseDto.java
  src/main/java/softee5/demo/entity/BaseTimeEntity.java
  src/main/java/softee5/demo/entity/History.java
  src/main/java/softee5/demo/entity/Image.java
  src/main/java/softee5/demo/entity/Member.java
  src/main/java/softee5/demo/entity/Memo.java
  src/main/java/softee5/demo/repository/HistoryRepository.java
  src/main/java/softee5/demo/repository/ImageRepository.java
  src/main/java/softee5/demo/repository/MemberRepository.java
  src/main/java/softee5/demo/service/HomeService.java
  src/main/java/softee5/demo/service/MemberService.java
  src/main/java/softee5/demo/service/MemoService.java
Labels: feat, refactor

#22 Win9 camera
  src/main/java/softee5/demo/controller/ImageController.java
  src/main/java/softee5/demo/dto/response/ImageLinkResponseDto.java
  src/main/java/softee5/demo/dto/response/ImageSaveResponseDto.java
  src/main/java/softee5/demo/entity/Image.java
  src/main/java/softee5/demo/service/ImageService.java
  src/main/java/softee5/demo/utils/S3Uploader.java
Labels: feat, fix

#26 Yang soeun/history
  src/main/java/softee5/demo/dto/ParkingLot.java
  src/main/java/softee5/demo/dto/response/HistoryDetailResponseDto.java
  src/main/java/softee5/demo/entity/Fee.java
  src/main/java/softee5/demo/entity/History.java
  src/main/java/softee5/demo/entity/Parking.java
  src/main/java/softee5/demo/repository/FeeRepository.java
  src/main/java/softee5/demo/repository/MemoRepository.java
  src/main/java/softee5/demo/response/BasicResponse.java
  src/main/java/softee5/demo/response/DataResponse.java
  src/main/java/softee5/demo/response/ErrorResponse.java
  src/main/java/softee5/demo/response/SuccessResponse.java
  src/main/java/softee5/demo/service/HomeService.java
  src/main/resources/data.sql
Labels: feat

#32 🛠[FIX] 데베 값 수정
  src/main/java/softee5/demo/service/HomeService.java
  src/main/java/softee5/demo/service/MemberService.java
  src/main/resources/data.sql
Labels: fix

#33 🎉[FEAT] history 최신순으로 내려주기
  src/main/java/softee5/demo/controller/ImageController.java
  src/main/java/softee5/demo/controller/ParkingController.java
  src/main/java/softee5/demo/repository/HistoryRepository.java
  src/main/java/softee5/demo/repository/ImageRepository.java
  src/main/java/softee5/demo/repository/MemberRepository.java
Labels: feat

#34 🎉[FEAT] home에 주차시작 시간 내려주기
  src/main/java/softee5/demo/dto/response/HomeResponseDto.java
  src/main/java/softee5/demo/service/HomeService.java
Labels: feat

#37 Yang soeun/response
  README.md
  src/main/java/softee5/demo/controller/HomeController.java
  src/main/java/softee5/demo/controller/ImageController.java
  src/main/java/softee5/demo/controller/LocationController.java
  src/main/java/softee5/demo/controller/ParkingController.java
  src/main/java/softee5/demo/dto/response/HistoryListResponseDto.java
  src/main/java/softee5/demo/exception/ExceptionController.java
  src/main/java/softee5/demo/response/BasicResponse.java
  src/main/java/softee5/demo/response/DataResponse.java
  src/main/java/softee5/demo/response/ErrorResponse.java
  src/main/java/softee5/demo/response/SingleResponse.java
  src/main/java/softee5/demo/response/SuccessResponse.java
  src/main/java/softee5/demo/service/HistoryService.java
  src/main/java/softee5/demo/service/HomeService.java
Labels: feat

#42 🛠[FIX] 히스토리 통계 코드 오류 수정
  src/main/java/softee5/demo/service/HistoryService.java
Labels: fix

#43 🛠[FIX] 주차 시작 시간 오류 나는 부분 수정
  src/main/java/softee5/demo/controller/LocationController.java
  src/main/java/softee5/demo/dto/request/UserDto.java
  src/main/java/softee5/demo/entity/BaseTimeEntity.java
  src/main/java/softee5/demo/entity/Member.java
  src/main/java/softee5/demo/repository/MemberRepository.java
  src/main/java/softee5/demo/service/LocationService.java
Labels: fix

#45 🛠[FIX] 히스토리 상세보기 dto 수정
  src/main/java/softee5/demo/dto/response/HistoryDetailResponseDto.java
  src/main/java/softee5/demo/repository/ImageRepository.java
  src/main/java/softee5/demo/service/HistoryService.java
Labels: fix
